import type { Metadata } from "next"
import { Arvo, Space_Grotesk, Jersey_10 } from "next/font/google"
import "./globals.css"
import { AntProvider } from "@/components/utilities/AntProvider"

const arvo = Arvo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arvo",
})
const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
})
const jersey_10 = Jersey_10({
  subsets: ["latin"],
  variable: "--font-jersey",
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${grotesk.className} ${jersey_10.variable} ${arvo.variable}  bg-dark-1000 w-screen text-dark-0 overflow-x-hidden`}
      >
        <AntProvider>{children}</AntProvider>
      </body>
    </html>
  )
}
